init:
  - git config --global core.autocrlf true

image: Visual Studio 2019

before_build:
  - choco install opencover.portable
  - choco install codecov

build_script:
  - cd scripts
  - ps: .\build-cake.ps1
  - OpenCover.Console.exe -register:administrator -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full ..\tests\Unit\SoftSentre.Shoppingendly.Services.Products.Tests.Unit.csproj" -filter:"+[SoftSentre.Shoppingendly.Services.Products*]* -[SoftSentre.Shoppingendly.Services.Products.Tests*]*" -output:".\softsentre_shoppingendly_services_products_coverage.xml" -oldstyle
  - codecov -f .\softsentre_shoppingendly_services_products_coverage.xml -t $(CODECOV_TOKEN)

test: off

branches:
  only:
    - develop
    - master

cache:
  - tools -> build.cake
  - packages -> build.cake
