init:
  - git config --global core.autocrlf true

image: Visual Studio 2019

before_build:
- choco install opencover.portable
- choco install codecov

build_script:
  - cd scripts
  - ps: .\build-cake.ps1
  - OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full ..\tests\Shoppingendly.Services.Products.Tests.Unit\Shoppingendly.Services.Products.Tests.Unit.csproj" -filter:"+[Shoppingendly.Services.Products*]* -[Shoppingendly.Services.Products.Tests*]*" -output:".\shoppingendly_services_products_coverage.xml" -oldstyle
  - codecov -f .\shoppingendly_services_products_coverage.xml -t $(CODECOV_TOKEN)

test: off

branches:
  only:
    - develop
    - master
    - implemented-domain-classes-in-tdd-approach

cache:
- tools -> build.cake
- packages -> build.cake