name: shoppingednly-services-products-build&tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core if needed
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - uses: actions/setup-dotnet@v1
      - name: build
        run: dotnet build Shoppingendly.Services.Products.sln --configuration Release
  tests:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core if needed
        uses: actions/setup-dotnet@v1.2.0
        with:
          dotnet-version: 3.1.100
      - uses: actions/checkout@v1
      - name: tests
        run: dotnet test Shoppingendly.Services.Products.sln --configuration Release
