name: shoppingednly-services-products-build&tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core if needed
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - uses: actions/setup-dotnet@v1
      - name: build
        run: dotnet build --configuration Release
  tests:
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core if needed
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - uses: actions/checkout@v2
      - name: tests
        run: dotnet test --configuration Release
